const kabupatenkota = {
    "Aceh": [
      "Kabupaten Aceh Barat",
      "Kabupaten Aceh Besar",
      "Kabupaten Aceh Jaya",
      "Kabupaten Aceh Selatan",
      "Kabupaten Aceh Singkil",
      "Kabupaten Aceh Tamiang",
      "Kabupaten Aceh Tengah",
      "Kabupaten Aceh Tenggara",
      "Kabupaten Aceh Timur",
      "Kabupaten Aceh Utara",
      "Kota Banda Aceh",
      "Kota Sabang",
      "Kota Lhokseumawe",
      "Kota Langsa",
      "Kota Subulussalam"
    ],
    "Sumatera Utara": [
      "Kabupaten Asahan",
      "Kabupaten Batubara",
      "Kabupaten Dairi",
      "Kabupaten Deli Serdang",
      "Kabupaten Humbang Hasundutan",
      "Kabupaten Karo",
      "Kabupaten Labuhan Batu",
      "Kabupaten Labuhan Batu Selatan",
      "Kabupaten Labuhan Batu Utara",
      "Kabupaten Langkat",
      "Kabupaten Mandailing Natal",
      "Kabupaten Nias",
      "Kabupaten Nias Barat",
      "Kabupaten Nias Selatan",
      "Kabupaten Nias Utara",
      "Kabupaten Padang Lawas",
      "Kabupaten Padang Lawas Utara",
      "Kabupaten Pakpak Bharat",
      "Kabupaten Samosir",
      "Kabupaten Serdang Bedagai",
      "Kabupaten Simalungun",
      "Kabupaten Tapanuli Selatan",
      "Kabupaten Tapanuli Tengah",
      "Kabupaten Tapanuli Utara",
      "Kabupaten Toba Samosir",
      "Kota Binjai",
      "Kota Gunungsitoli",
      "Kota Medan",
      "Kota Padang Sidempuan",
      "Kota Pematang Siantar",
      "Kota Sibolga",
      "Kota Tanjung Balai",
      "Kota Tebing Tinggi"
    ],
    "Jawa Barat": [
      "Kabupaten Bandung",
      "Kabupaten Bandung Barat",
      "Kabupaten Bekasi",
      "Kabupaten Bogor",
      "Kabupaten Ciamis",
      "Kabupaten Cianjur",
      "Kabupaten Cirebon",
      "Kabupaten Garut",
      "Kabupaten Indramayu",
      "Kabupaten Karawang",
      "Kabupaten Kuningan",
      "Kabupaten Majalengka",
      "Kabupaten Pangandaran",
      "Kabupaten Purwakarta",
      "Kabupaten Subang",
      "Kabupaten Sukabumi",
      "Kabupaten Sumedang",
      "Kabupaten Tasikmalaya",
      "Kota Bandung",
      "Kota Banjar",
      "Kota Bekasi",
      "Kota Bogor",
      "Kota Cimahi",
      "Kota Cirebon",
      "Kota Depok",
      "Kota Sukabumi",
      "Kota Tasikmalaya"
    ],
  };
